### PR TITLE
Merge pull request #18 from MiracleFactory/main

### PR DESCRIPTION
**Pull request by Devemmy01**
merge

### CODE REVIEW

**Comment by YuelinXin** [comment]
I don't think this is necessary, dev is always going to be some where behind / ahead of main

**Comment by YuelinXin** [comment]
You can ignore these types of changes (where no files is changed)

**Comment by Devemmy01** [comment]
> You can ignore these types of changes (where no files is changed)

Oh thanks for the info. I never knew

**Comment by YuelinXin** [comment]
> > You can ignore these types of changes (where no files is changed)
> 
> Oh thanks for the info. I never knew

No worries, look forward to code with you in the future :)

**Pull request merged**
